<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>fr.miage</groupId><artifactId>ateliers-debutants</artifactId><version>1.0.0</version><packaging>pom</packaging><modules><module>01-demarrage</module><module>02-http-json</module><module>03-injection</module><module>04-crud</module><module>05-persistance</module><module>06-tests</module><module>07-client</module><module>08-messages</module></modules></project>